# Generated by Django 4.2 on 2023-05-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
