# Generated by Django 5.0.4 on 2024-10-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredients',
            new_name='decription',
        ),
    ]
