# Generated by Django 4.2 on 2023-06-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivered_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='home_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='sub_city',
        ),
    ]
